import type { BeadProduct } from "@/types";

export const BEADS: BeadProduct[] = [
  {
    id: "dignity-4mm",
    name: "Dignity 4mm",
    beadType: "Dignity",
    glbPath: "/models/beads/Dignity_4mm.glb",
    diameter: 0.004,
    sku: "000888884444",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 4,
  },
  {
    id: "dignity-5mm",
    name: "Dignity 5mm",
    beadType: "Dignity",
    glbPath: "/models/beads/Dignity_5mm.glb",
    diameter: 0.005,
    sku: "11112222233344",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 5,
  },
  {
    id: "dignity-6mm",
    name: "Dignity 6mm",
    beadType: "Dignity",
    glbPath: "/models/beads/Dignity_6mm.glb",
    diameter: 0.006,
    sku: "222233334444",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 6,
  },
  {
    id: "admire-6mm",
    name: "Admire 6mm",
    glbPath: "/models/beads/Admire_6mm.glb",
    beadType: "Admire",
    diameter: 0.006,
    sku: "00000",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 6,
  },
  {
    id: "admire-8mm",
    name: "Admire 8mm",
    glbPath: "/models/beads/Admire_8mm.glb",
    beadType: "Admire",
    diameter: 0.008,
    sku: "30439039503",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 8,
  },
  {
    id: "honesty-6mm",
    name: "Honesty 6mm",
    glbPath: "/models/beads/Honesty_6mm.glb",
    beadType: "Honesty",
    diameter: 0.006,
    sku: "30439039503",
    beadCategory: "bead",
    material: "gold",
    sizeMm: 6,
  },
  {
    id: "honesty-10mm",
    name: "Honesty 10mm",
    glbPath: "/models/beads/Honesty_10mm.glb",
    beadType: "Honesty",
    diameter: 0.010,
    sku: "4080838287",
    beadCategory: "bead",
    material: "metal",
    sizeMm: 10,
  },
  {
    id: "harmony",
    name: "Harmony",
    glbPath: "/models/beads/Harmony.glb",
    beadType: "Harmony",
    diameter: 0.005,
    sku: "4080838287",
    beadCategory: "tube",
    material: "gold",
    sizeMm: 5,
  },

  // ── Charms ──────────────────────────────────────────────────────────────────
/**
  {
    id: "blessed-disc",
    name: "Blessed Disc",
    glbPath: "/models/charms/Blessed_Charm/Blessed_Disc.glb",
    beadType: "Blessed Disc",
    diameter: 0.005,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 12,
  },
  {
    id: "blessed-disc-small",
    name: "Blessed Disc Small",
    glbPath: "/models/charms/Blessed_Charm/Blessed_Disc_Small.glb",
    beadType: "Blessed Disc",
    diameter: 0.008,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 8,
  },
  {
    id: "classic-charm-10mm",
    name: "Classic Charm 10mm",
    glbPath: "/models/charms/Classic_Charm/Classic_Charm_10mm.glb",
    beadType: "Classic Charm",
    diameter: 0.010,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 10,
  },
  {
    id: "classic-charm-8mm",
    name: "Classic Charm 8mm",
    glbPath: "/models/charms/Classic_Charm/Classic_Charm_8mm.glb",
    beadType: "Classic Charm",
    diameter: 0.008,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 8,
  },
  {
    id: "inspire-charm",
    name: "Inspire Charm",
    glbPath: "/models/charms/Inspire_Charm/Inspire_Charm.glb",
    beadType: "Inspire Charm",
    diameter: 0.012,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 12,
  },
  {
    id: "inspire-charm-small",
    name: "Inspire Charm Small",
    glbPath: "/models/charms/Inspire_Charm/Inspire_Charm_Small.glb",
    beadType: "Inspire Charm",
    diameter: 0.008,
    sku: "",
    beadCategory: "charm",
    material: "gold",
    sizeMm: 8,
  },
*/
];
